Module2 task1
htmlacademy-adaptive/2287845-cat-energy-28 pull request #10
Opened 2023-04-03 17:48 UTC by U1ix

2023-04-07 15:32 UTC, DKukushkin91 requested changes

2023-04-07 15:32 UTC, DKukushkin91 commented on source/catalog.html
> +<!--ХЭДЕР-->
Комментариев в html не нужно

2023-04-07 15:32 UTC, DKukushkin91 commented on source/catalog.html
> +        <li class="nav-list__item nav-list__item--active">
Нарушен бэм, откуда не возьмись появился блок `nav-list`, можно было просто назвать `nav__item`

2023-04-07 15:32 UTC, DKukushkin91 commented on source/catalog.html
> +<!--МЭЙН-->
Комментарии все убери из html

2023-04-07 15:32 UTC, DKukushkin91 commented on source/catalog.html
> +<main class="catalog">
`main` стоит оставить класс `main` а внутри него сделать `section class='catalog'`

2023-04-07 15:32 UTC, DKukushkin91 commented on source/catalog.html
> +          <dt class="">Масса</dt>
`catalog__item-terms`

2023-04-07 15:32 UTC, DKukushkin91 commented on source/catalog.html
> +          <dd class="">500 г</dd>
`catalog__item-description`

2023-04-07 15:32 UTC, DKukushkin91 commented on source/catalog.html
> +      <div class="catalog__item-description">
это `catalog__item-descriptions`

2023-04-07 15:32 UTC, DKukushkin91 commented on source/catalog.html
> +  <section class="catalog__section additional">
у section можно задать класс `section` а не `catalog__section` не нужно его брать как элемент блока

2023-04-07 15:32 UTC, DKukushkin91 commented on source/catalog.html
> +        <div class="additional__item-description">
по аналогии с кодом выше, `descriptions` и т.д

2023-04-07 15:32 UTC, DKukushkin91 commented on source/catalog.html
> +      </li>
не хватает еще 1 элемента списка
![изображение](https://user-images.githubusercontent.com/62586082/230634035-e869aa9c-437f-4fe7-a520-0229ffa67112.png)

2023-04-07 15:32 UTC, DKukushkin91 commented on source/catalog.html
> +      </li>
даже несколько элементов списка нет

2023-04-07 15:32 UTC, DKukushkin91 commented on source/form.html
> +<main class="main-form">
это класс `main`

2023-04-07 15:32 UTC, DKukushkin91 commented on source/form.html
> +  <section class="main-form__selection selection">
`class='section selection'`

и всё же глагол не очень хороший выбор для класса, бери существительные всегда, например: `program`

2023-04-07 15:32 UTC, DKukushkin91 commented on source/form.html
> +            <label class="form-info__input">ИМЯ:*
всё хорошо, но текст нужно обернуть в `span`. Касается всех похожих блоков где текст не обернут

2023-04-07 15:32 UTC, DKukushkin91 commented on source/form.html
> +      <fieldset class="selection-form__data-form data-form">
`contacts-form`

2023-04-07 15:32 UTC, DKukushkin91 commented on source/index.html
> +
Лишний отступ

2023-04-07 15:32 UTC, DKukushkin91 commented on source/index.html
> +            <h3 class="catalog-preview__heading">похудение</h3>
Касается всего проекта, причем говорил это на созвоне. Не должно быть у одного и того же по смыслу элемента разных склонений heading / title / caption и т.д., назвал title значит все заголовки на сайте должны быть `твой-блок__title` и т.п

2023-04-07 15:32 UTC, DKukushkin91 commented on source/index.html
> +
лишний отступ

2023-04-07 15:32 UTC, DKukushkin91 commented on source/index.html
> +
лишний отступ

2023-04-07 15:32 UTC, DKukushkin91 commented on source/index.html
> +
лишний отступ

2023-04-07 15:32 UTC, DKukushkin91 commented on source/index.html
> +    <!--МЭЙН-->
удали комиты

2023-04-08 15:55 UTC, DKukushkin91 requested changes

2023-04-08 15:55 UTC, DKukushkin91 commented on source/catalog.html
> +            <dt class="">Масса</dt>
где классы?

2023-04-08 15:55 UTC, DKukushkin91 commented on source/catalog.html
> +            <dt class="">Масса</dt>
где классы?

2023-04-08 15:55 UTC, DKukushkin91 commented on source/catalog.html
> +            <dd class="">500 г</dd>
где классы?

2023-04-08 15:55 UTC, DKukushkin91 commented on source/catalog.html
> +            <dd class="catalog__item-description">500 г</dd>
2 одинаковых класса? `<div class="catalog__item-description">` `<dd class="catalog__item-description">`

2023-04-08 15:55 UTC, DKukushkin91 commented on source/catalog.html
> +        <div class="catalog__item-description">
Нужно изменить на `__item-descriptions`

2023-04-08 15:55 UTC, DKukushkin91 commented on source/catalog.html
> +      </li>
Так и не появился элемент в разметке!

2023-04-08 15:55 UTC, DKukushkin91 commented on source/catalog.html
> +              <dt class="">1 литр</dt>
отсутствуют классы

2023-04-08 15:55 UTC, DKukushkin91 commented on source/catalog.html
> +              <dt class="">5 литров</dt>
отсутствуют классы

2023-04-08 15:55 UTC, DKukushkin91 commented on source/catalog.html
> +              <dt class="">1 упаковка (100 г)</dt>
отсутствуют классы

2023-04-08 15:55 UTC, DKukushkin91 commented on source/catalog.html
> +              <dt class="">1 упаковка (30 г)</dt>
отсутствуют классы

2023-04-08 15:55 UTC, DKukushkin91 commented on source/form.html
> +            <label class="form-info__input">ИМЯ:*
ты поставил класс, но ничего не исправил

2023-04-08 15:55 UTC, DKukushkin91 commented on source/form.html
> +            <label class="form-info__input">ИМЯ:*
Классы так же названы не очевидно, почему у label класс input?
 
 Пример как надо.
 
 
     <label class="form-info__label">
         <span class='form-info__text'>ИМЯ:*</span>
         <input class="form-info__input" type="text" name="name" placeholder="Барсик">
    </label>

2023-04-08 15:55 UTC, DKukushkin91 commented on source/index.html
> +          <div class="example__slimming slimming">
класс не должен описывать то что происходит внутри. Это должно быть что то общее.
Есть блок example это он и остался.
можно назвать это example__slider example-slider

2023-04-08 15:55 UTC, DKukushkin91 commented on source/index.html
> +        <div class="example__cost cost">
для чего тут выделять отдельный блок?

2023-04-09 17:30 UTC, DKukushkin91 requested changes

2023-04-09 17:30 UTC, DKukushkin91 commented on source/catalog.html
> +            <dd class="catalog__item-menu">500 г</dd>
`item-description` я же писал это.

2023-04-09 17:30 UTC, DKukushkin91 commented on source/catalog.html
> +      </li>
Ну еще 1 попытка добавить элемент...

2023-04-09 17:30 UTC, DKukushkin91 commented on source/catalog.html
> +              <dd class="additional__item-menu">100 ₽</dd>
dd это все `__item-description`

2023-04-09 17:30 UTC, DKukushkin91 commented on source/form.html
> +        <textarea name="comment" cols="30" rows="10">Расскажите обо всех повАдках кота</textarea>
опечатка

2023-04-09 17:30 UTC, DKukushkin91 commented on source/form.html
> +          <span class="form-info__span">Дополнительно</span>
не тот класс

2023-04-09 17:30 UTC, DKukushkin91 commented on source/form.html
> +    <p class="programn-form__text">* — Обязательные поля</p>
текст должен быть в `form`

2023-04-09 17:30 UTC, DKukushkin91 commented on source/index.html
> +            <h3 class="catalog-preview__item-title">Набор массы</h3>
почему классы отличаются у одинаковых элементов? Сделай идентичные классы для элементов списка

2023-04-09 17:30 UTC, DKukushkin91 commented on source/index.html
> +        <div class="example__cost ">
а где класс `example-cost` добавь

2023-04-09 18:42 UTC, U1ix commented on source/catalog.html
> +      </li>
доавил элемент)

2023-04-10 14:11 UTC, DKukushkin91 requested changes

2023-04-10 14:11 UTC, DKukushkin91 commented on source/form.html
> +            <label class="contacts-form__input">E-mail:*
Где обертка для текста в `<span>` касается всех подобных `input + label`

2023-04-10 15:57 UTC, DKukushkin91 approved these changes

2023-04-10 15:57 UTC, merged