Добавляет новую ветку
htmlacademy-adaptive/2287845-cat-energy-28 pull request #13
Opened 2023-04-28 15:11 UTC by U1ix

2023-05-05 16:13 UTC, DKukushkin91 requested changes
В целом всё отлично, ты не учел критерий, что при отсутствии JS у тебя меню должно быть показано всегда, сейчас его нет

![изображение](https://user-images.githubusercontent.com/62586082/236511565-4eecdeba-1ed2-47b0-8405-34a9ca859add.png)

2023-05-05 16:13 UTC, DKukushkin91 commented on git status
> +* [32mmodule3-task1[m
Это что?) Удали этот файл

2023-05-05 16:13 UTC, DKukushkin91 commented on source/form.html
> +          <legend class="form-info__text-container">
legend может быть только в fieldset, div не может быть родителем legend тэга, разметка не проходит валидацию

2023-05-05 16:13 UTC, DKukushkin91 commented on source/form.html
> +          <legend class="contacts-form__legend">Контактные данные (владельца кота)</legend>
legend может быть только в fieldset, div не может быть родителем legend тэга, разметка не проходит валидацию

2023-05-05 16:13 UTC, DKukushkin91 commented on source/form.html
> +          <legend class="comment-form__text">
legend может быть только в fieldset, div не может быть родителем legend тэга, разметка не проходит валидацию

2023-05-05 16:13 UTC, DKukushkin91 commented on source/form.html
> +          <legend class="extra-form__legend">
legend может быть только в fieldset, div не может быть родителем legend тэга, разметка не проходит валидацию

2023-05-05 16:13 UTC, DKukushkin91 commented on source/form.html
> +          <textarea class="comment-form__description" name="comment" cols="40" rows="7  ">Расскажите обо всех повадках кота</textarea>
Пробелы в атрибуте `rows` нужно убрать. Вообще нажми в каждом html `ctrl + alt + L` отформатируй код, читать тяжело

2023-05-05 16:13 UTC, DKukushkin91 commented on source/sass/components/catalog.scss
> +  border-bottom: 1px solid #d9d9d9;
Переменная?

2023-05-05 16:13 UTC, DKukushkin91 commented on source/sass/components/form-radio.scss
> +.form-radio {
Родительский блок, ниже чем блок элемента, не надо так см 1 строку в этом файле, опусти её ниже .form-radio

2023-05-05 16:13 UTC, DKukushkin91 commented on source/sass/components/hero.scss
> +  padding: 11px 11px;
```padding: 11px;``` сделает тоже самое и будет короче по записи

2023-05-05 16:13 UTC, DKukushkin91 commented on source/sass/components/form-radio.scss
> +    left: 23%;
стили 
```
top и left
```

замени на: 

```
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
```

2023-05-07 14:28 UTC, DKukushkin91 requested changes

2023-05-07 14:28 UTC, DKukushkin91 commented on source/form.html
> +      <div class="form-info__container middle-container">
Нарушения именования классов по бэм, у тебя блок ```program-form```

2023-05-07 14:28 UTC, DKukushkin91 commented on source/sass/components/catalog.scss
> +  display: inline-block;
если используешь inline-block обязательно указывай vertical-align

2023-05-14 18:44 UTC, DKukushkin91 requested changes

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/about-products.scss
> +    padding: 40px 26px 57px 0;
Это тут не нужно

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/about-products.scss
> +    column-gap: 153px;
row-gap: 37px; добавь
column-gap: 20px; больше и не надо, меньше тоже

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/about-products.scss
> +    justify-content: flex-start;
space-between

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/about-products.scss
> +    column-gap: 153px;
добавь padding-right: 74px;

2023-05-14 18:44 UTC, DKukushkin91 commented on source/catalog.html
> -    <section class="catalog__section additional">
Эта секция не должна быть вложена в другую секцию, вынеси её
Должно быть так:
![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/b4f03955-91bd-403f-b248-c33987867ca4)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +  border-bottom: 1px solid $grey-3;
Бордер задается 1 элементу списка. Ну или самому списку ```additional__list```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +  padding: 0 0 36px;
падинг нужно убрать

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +    padding: 0 36px 80px 36px;
Убрать

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +    margin: 0 0 26px 0;
тут не должно быть как раз margin, его нужно занулить

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +    gap: 55px;
margin: 0

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +    justify-content: space-between;
тут как раз нужно задать отступ вниз.
![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/401e9fae-1c59-4ec9-8d4d-a59f13ab86a1)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +    width: 100%;
Сначала задется ширина в процентах, потом max-width

```
width: 100%;
max-width: 610px;
```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +    gap: 178px;
Прекрати пользоваться ```gap```, задавай отступы только для необходимых направлений, ```row``` / ```column```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +    justify-content: space-between;
Задай ```column-gap```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +    justify-content: space-between;
хотя бы чисто для избежания таких прилипаний, 20px будет достаточно


![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/b2e2b5a3-5581-4766-8ae4-468e2ac1866f)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +    justify-content: space-between;
И посмотри что с суммой, рубли уехали

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/lib/vars.scss
> +$tablet-width: 769px;
768px;

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +    width: unset;
width: fit-content либо width: auto

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/additional.scss
> +    justify-content: unset;
flex-start ровно unset

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog.scss
>  .catalog__title {
Нужно добавить .catalog__section с правилом overflow:hidden

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog.scss
> +    width: 100vw;
200vw

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog.scss
> +.catalog__item {
Карточка не соответствует макету, ты зачем - то сделал её на флексах, сделай на гридах 

![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/51a02de1-df2d-4a89-bad5-9d04d357a264)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/catalog.html
> -          <a class="catalog-add__add" href="#">
Убери эту ссылку. Тут просто иконка

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog-add.scss
> +  margin: 25px 0 23px 0;
не нужны марджины вообще кроме ```margin-bottom```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog-preview.scss
> +      width: 100px;
На десктопе враппер не должен быть абсолютно спозиционированным

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog-preview.scss
> +    margin: 0 0 73px;
тут не должно быть margin это ребенок, он не должен распирать родителя. С этим справится сам ```wrapper```

![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/67c2d2b0-ece6-4dea-a25a-f679bf575d4c)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog-preview.scss
> +  margin: 0 0 22px;
тут не должно быть margin это ребенок, он не должен распирать родителя. С этим справится сам ```wrapper```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog-preview.scss
>    display: flex;
При внесении контента в элемент, не должно быть так, что 1 item сжимает другой, так же вне зависимости от количества текста, ссылка каталога должна быть снизу

![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/28c7b685-08dd-4df7-b8d6-f6d69c88eeb5)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog-preview.scss
>    display: flex;
с ссылкой поможет flex:1 для .catalog-preview__item-description

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog-preview.scss
> +    padding: 77px 37px 55px 52px;
```margin-bottom: 0```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog-preview.scss
> +  padding-top: 15px;
```width: fit-content``` ссылка не должна иметь "невидимую область для клика"

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog.scss
> +  margin: 0 0 19px 0;
Для правильного отображения бордера, нужно вынести тайтл сюда

![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/c79fe72c-0949-4a3f-9563-a718a435cc85)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog.scss
> +  &::after {
тогда это не понадобится (и это к лучшему)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog.scss
> +  @media (min-width: $tablet-width) {
2 ое медиа выражение не нужно, ты просто пишешь всё в 1ом

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog.scss
> +  }
когда наполняем контентом, всё едет

![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/311b20a3-7f7e-463b-8438-4953ac00cd19)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/catalog.scss
> +    border-bottom: 1px solid #e7e7e7e7;
переменную используй

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/comment-form.scss
> +  padding: 9px 0 15px 15px;
Padding должен быть со всех сторон

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/comment-form.scss
> +  max-width: 280px;
вообще max-width не нужен

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/comment-form.scss
> +
Задай resize: vertical;

2023-05-14 18:44 UTC, DKukushkin91 commented on source/form.html
> +                  <input class="form-info__input" type="text" name="weight" placeholder="7">
Все инпуты отмеченные звездочкой, имеют атрибут required (поля обязательные для заполнения)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/comment-form.scss
> +    grid-column: 1/3;
мы говорили об этом, если будет 33 колнки, будем каждый раз заходить и менять в стили?

задай 
```
grid-column: 1 / -1;
```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/comment-form.scss
> +    margin: 0 0 76px 0;
Все отступы должны быть у ```coment-form__text```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts-form.scss
> +    grid-column: 1/2;
1 / -1

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts-form.scss
> +    grid-template-columns: repeat(2, 100%);
нельзя задать repeat(2, 100%); у тебя в итоге 2 ребенка вылезли за родителя.

Используй единицы измерения для гридов ```fr``` , ```repeat(2, 1fr);```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts-form.scss
>  .contacts-form__data {
Отступы нужны внутри ипнута, в том числе и с стороны иконки, иначе происходит это
![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/214fe24f-b15d-4d4c-b1b5-610d28de33ca)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts-form.scss
> +  display: inline;
Зачем это? Убираем

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts.scss
> +    grid-area: 1/1;
удали это

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/middle-container.scss
>    margin: 0 auto;
Задай обязательно width: 100%;

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts.scss
> +  background: $white;
display: grid;

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts.scss
> +  background: $white;
Лучше выбрать серый фон, что бы был контраст с блоком контактов

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts.scss
>  .contacts__container {
удалить вообще

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts.scss
> +.contacts__text-container {
Вот его нужно обернуть в middle-container

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts.scss
> +.contacts__text-container {
Вот как выглядит эта секция 
![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/fd6d8a9b-331a-41d1-aca8-0940918cde6b)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts.scss
> +.contacts__text-container {
Для миддл контейнера задай еще доп класс contacts_container например и там добавь 

```
grid-area: 1 / -1;
Дальше сам сориентируйся по отступам и т.п

```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts.scss
> +    justify-self: center;
и это

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts.scss
> +    transform: translateY(76px);
и это

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts.scss
> +    position: absolute;
и это

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/contacts.scss
> +    left: 104px;
и это

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/example-cost.scss
> +  margin: 104px 0 0 0;
example__cost example-cost Это цена, а у тебя это картинки вообще

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/example-slider.scss
>  .example-slider {
example__slider example-slider это сейчас у тебя не слайдер, а какие - то блоки example_descriptions или example_features

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/example.scss
> +    position: absolute;
Это не абсолютно спозиционированный элемент

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/example.scss
> +    padding: 0 600px 0 0;
Надо бурать

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/example-slider.scss
> +
Нужно задать max-width

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/extra-form.scss
> +.extra-form__label {
чекбоксу плохо
Излечит его 

```
flex-shrink: 0;
align-self: flex-start;
```

![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/b675c93a-de17-41ff-8805-43b044169456)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/form-info.scss
> +    grid-column: 2/1;
просто 1

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/form-info.scss
> +    grid-column: 2/1;
убери отступы, пользуйся гапами в родителе

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/form-info.scss
> +    grid-column: 2/1;
padding: 0, margin: 0

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/form-radio.scss
> +    grid-column: 2/2;
grid-column: 2

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/form-radio.scss
> +    margin: auto 0;
Я говорил в телеге, это не легенда, этот блок относится к заголовку страницы, это его подзаголовок
![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/3742ac81-2be9-4f2a-a5b7-bd3488b63a8b)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/form-radio.scss
> +    margin: auto 0;
Поэтому тут этот margin вообще не нужен

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/form-radio.scss
> +  border-radius: 50%;
flex-shrink: 0; align-self: flex-start

![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/4e7aa9c6-51a8-4a72-98e1-79809a71ac6d)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/header.scss
>    &--form {
все внутренние вертикальные отступы должны быть от хэдера, никак не от детей

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/hero.scss
> +  margin-top: -136px;
Не используй отрицательные мэрджины для позиционирования

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/middle-container.scss
> +    padding: 0 110px;
не нужны padding тут просто пусть будут с планшета на 30 px, т.е указывать их не нужно

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/nav.scss
> +    gap: 36px;
Не используй gap, пиши конкретно ```column-gap``` ```row-gap```

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/nav.scss
> +      margin-bottom: -10px;
не используй отрицательные отступы

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/hero.scss
> +.hero {
https://cat-energy.vercel.app/ пример главной.

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/present.scss
> +    grid-column: 3/3;
Надо переверстывать всю секцию, которую ты вложил зачем то в другую секцию, короч получилось очень не очень
Тут просто 1 отдельная секция additional вне секции каталога, и в себе других секций не содержит
![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/0689108d-8a89-4d27-823b-d33f4e038c67)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/program-form.scss
> +    padding: 26px 188px;
Зачем такие башенные паддинги, достаточно вертикальных 20пх край 

у тебя сейчас просто кнопка 1 сплошной падинг
![изображение](https://github.com/htmlacademy-adaptive/2287845-cat-energy-28/assets/62586082/6130ca80-dfa4-4c34-a8de-0347e2ca1d9e)

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/program-form.scss
> +    grid-column: 1/3;
1 / -1

2023-05-14 18:44 UTC, DKukushkin91 commented on source/sass/components/program.scss
> +    margin: 65px 0 54px 40px;
Левый margin не нужен пользуйся padding

2023-05-15 11:44 UTC, U1ix commented on source/sass/components/additional.scss
> +    width: unset;
width убрал

2023-05-15 13:04 UTC, U1ix commented on source/sass/components/catalog-preview.scss
>    display: flex;
над этим заданием нужна помощь(((

2023-05-15 13:13 UTC, U1ix commented on source/sass/components/catalog.scss
> +  margin: 0 0 19px 0;
Здесь не понял(

2023-05-15 13:17 UTC, U1ix commented on source/sass/components/catalog.scss
> +  margin: 0 0 19px 0;
Обратно понял сделал_)

2023-05-15 17:32 UTC, U1ix commented on source/sass/components/example-cost.scss
> +  margin: 104px 0 0 0;
здесь не понятно о чем говорится

2023-05-15 19:28 UTC, U1ix commented on source/sass/components/hero.scss
> +  margin-top: -136px;
не смог сделать

2023-05-16 16:16 UTC, U1ix commented on source/sass/components/example-cost.scss
> +  margin: 104px 0 0 0;
Нужна помощь

2023-05-16 16:16 UTC, U1ix commented on source/sass/components/example-slider.scss
>  .example-slider {
Нужна помощь

2023-05-16 16:16 UTC, U1ix commented on source/sass/components/example.scss
> +    position: absolute;
и здесь

2023-05-18 16:20 UTC, merged